### ISSUE TITLE
How was the q/g nsubs data generated?

### ISSUE THREAD

**Issue by andrewjohnlowe** [pkomiske/EnergyFlow#14]
Hello,

The documentation here:
[https://energyflow.network/docs/datasets/#quark-and-gluon-nsubs](https://energyflow.network/docs/datasets/#quark-and-gluon-nsubs)
says that the q/g nsubs data is "A dataset consisting of 45 N-subjettiness observables for 100k quark and gluon jets generated with Pythia 8.230". But I don't see any other notes.

The kind of information I'm interested in: what were the processed used, at what sqrt(s), how were the final state particles clustered, which jet algo, which software, what kinematics cuts were applied, and was there any detector simulation, and what kind. 

I'm looking for similar information as shown for the other q/g data:
[https://energyflow.network/docs/datasets/#quark-and-gluon-jets](https://energyflow.network/docs/datasets/#quark-and-gluon-jets)

Also, are there any papers using the nsubs dataset, for comparison of results?

FInally -- and importantly -- how do I cite use of your dataset? I don't see a DOI or a Zenodo link.

Thanks!

**Comment by pkomiske** [comment]
Hi Andrew,

That N-subjettiness dataset corresponds to the Pythia 8.226 (uds) quark/gluon dataset that is also hosted on EnergyFlow so check that out for the details. For citing it, it was used in the Energy Flow Network paper, 1810.05165, so please cite that. Let us know if you have any more questions.

Patrick

On Jan 15, 2020, at 12:57 PM, Dr Andrew John Lowe <notifications@github.com> wrote:

﻿

Hello,

The documentation here:
https://energyflow.network/docs/datasets/#quark-and-gluon-nsubs
says that the q/g nsubs data is "A dataset consisting of 45 N-subjettiness observables for 100k quark and gluon jets generated with Pythia 8.230". But I don't see any other notes.

The kind of information I'm interested in: what were the processed used, at what sqrt(s), how were the final state particles clustered, which jet algo, which software, what kinematics cuts were applied, and was there any detector simulation, and what kind.

I'm looking for similar information as shown for the other q/g data:
https://energyflow.network/docs/datasets/#quark-and-gluon-jets

Also, are there any papers using the nsubs dataset, for comparison of results?

FInally -- and importantly -- how do I cite use of your dataset? I don't see a DOI or a Zenodo link.

Thanks!

**Comment by andrewjohnlowe** [comment]
So the n-subjettiness dataset is derived from [https://zenodo.org/record/3164691#.XiBLfshKhmM](https://zenodo.org/record/3164691#.XiBLfshKhmM), with the n-subjettiness observables built from the jet constitutents (particles) in the parent dataset? OK, that being the case, please feel free to close.
