### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by RoyHirsch** [pkomiske/EnergyFlow#18]
Hi, while trying to run your code  I encountered the following problem:
ImportError: cannot import name 'PFN' from 'energyflow.archs'

Will appreciate your respond,

**Comment by pkomiske** [comment]
Can you send some more information about your setup? Specifically:

- Your OS (linux, macOS, Windows, etc.)
- Your Python version and distribution (CPython, Anaconda, PyPy, etc.)
- The EnergyFlow version you're running
- Keras/Tensorflow versions

I'm able to run `from energyflow.archs import PFN` just fine using Python 3.7 on macOS/linux, the latest EnergyFlow, Keras 2.4.3, and Tensorflow 2.2.0.

**Comment by RoyHirsch** [comment]
Hi Tnx I had a local installation problem and now it is working proparly,
