### ISSUE TITLE
Issue Importing EFN Package

### ISSUE THREAD

**Issue by kevbauer** [pkomiske/EnergyFlow#2]
There appears to be some circular dependent imports. I was able to install EnergyFlow fine with pip but when I went to run the efn_example.py I get the import error:

----> 1 from energyflow.archs import EFN

ImportError: cannot import name EFN

From this stackoverflow topic (https://stackoverflow.com/questions/9252543/importerror-cannot-import-name-x) the issue seems to be in circular dependencies.

**Comment by pkomiske** [comment]
What version of python and energyflow are you running? I can't seem to reproduce that error with either python 2 or 3 for the latest two versions, 0.10.4 and 0.10.5, running on macOS.

Perhaps check that Keras and a backend (e.g. TensorFlow) are set up properly?

**Comment by kevbauer** [comment]
I have version 0.10.5 working now on python 3.6 The issue was that I needed to import keras before importing EFN. I created a merge request with this minor change to the example. Thanks!

**Comment by ericmetodiev** [comment]
I was able to artificially reproduce the same ImportError by first uninstalling Keras and then trying to import EFN. Given that you seem to be running into this error with Keras installed, perhaps this indicates that a check in the architectures init file is failing.

Are there other UserWarnings associated with the error? When I remove Keras and try it they are of the form:
`UserWarning: could not import some architectures - No module named 'keras'`

**Comment by kevbauer** [comment]
Hmmm well I can't seem to reproduce the same error I was seeing before. The example mysteriously works fully out of the box for me now. 

Perhaps I was mistakenly using a different python environment, which didn't have keras installed, although I don't remember a warning message about keras. 

Either way it's fixed now even if I don't understand the previous issue. Thanks for your help!
