### ISSUE TITLE
norm=True causes jet constituents to be outside of simplex

### ISSUE THREAD

**Issue by mattleblanc** [pkomiske/EnergyFlow#8]
Hi all,

I see errors from POT when I try to turn on the `norm=True` option when calculating EMDs:

```
/usr/local/lib/python2.7/site-packages/energyflow/emd.py:255: UserWarning: Problem infeasible. Check that a and b are in the simplex
```

These are thrown for jets which seem to be otherwise working just fine: if I don't try to normalise the pT's, then I get EMDs out which are comparable to the ones in the demo you provide, if I also disable the normalisation in that calculation.

Is there something I need to be aware of when using this option? I'm interested in trying to re-derive the plots from the EMD demo using my own input jets, and the correlation dimension example seems to depend on this normalisation switch being turned on (or at least, it is done in the demo -- I don't see details about this being done in your paper?).

Cheers,
Matt

**Comment by pkomiske** [comment]
Hi Matt,

The "Problem infeasible" warning coming from POT can mean many things. Most commonly it means that the sum of the weights (or energies, pTs, etc) is not the same between the two events. `norm=False` deals with this by adding an extra particle to make up the difference (effectively implementing the second term in Eq. 1 of [our paper](https://arxiv.org/abs/1902.02346)) and `norm=True` deals with this by normalizing the weights to sum to 1 for each event. If the event has no particles, it's possible that you could get this error in the latter case and not the former.

Unfortunately, "Problem infeasible" also pops up when there are slight numerical issues in the convergence of the solution inside POT. I've only ever had this happen on OSX with a lot of particles in the event. Hopefully this is not what's going on, since fixing that essentially requires fixing POT. EnergyFlow 0.12.2 tried to mitigate this potential problem by internally scaling the weights to be near 1 (to help with numerics) and then restoring the correct units at the end.

If it turns out that the problem was empty events, then I should probably consider adding an explicit check for this case with a cleaner error message.

Patrick

**Comment by mattleblanc** [comment]
Hi Patrick,

I am running this on OSX, witth 0.12.2. I don't think the error is empty jets, as I don't seem to have any jets without constituents passing the (basic) selections I place on them. Maybe this is a problem with POT directly, then?

MLB

**Comment by pkomiske** [comment]
My best guess then is that it is an issue with POT. To confirm that (and hopefully to figure out a solution), would you be able to provide in a text file two jets that have this problem? In the meantime, I'm curious what happens if you run on Linux instead of OSX, because we've observed that to fix the problem for jets with typical constituent multiplicities.

**Comment by mattleblanc** [comment]
Not a problem -- I've put two problematic jets here, the columns should be (pt,y,phi), though it is before they are centered on their pt-centroid, etc.: 

https://gist.github.com/mattleblanc/e564f17b9dbc5093ef701efbdb82e0f0

Trying to run `ef.emd.emds` with just an input array of these two jets causes the message to be thrown. 

I find it weird that this message never pops up with the jets supplied by your package: in theory they should be very similar, as I generate these ones in Pythia using the same processes you mention in the documentation, e.g.

```
  pythia.readString("WeakBosonAndParton:qqbar2gmZg = on");
  pythia.readString("WeakBosonAndParton:qg2gmZq = on");
```

I can try to run my scripts in a linux environment, though it might not happen so quickly. I'll report back when I test it out.

**Comment by pkomiske** [comment]
So we’ve tried computing EMD on these example jets (with no additional processing, e.g. centering) and don’t run into any issues, even on OSX, for python 2.7, 3.6, and 3.7.

Is the issue appearing before the centering step or only after? Can you send which versions of energyflow, pot, and python you are using?

**Comment by mattleblanc** [comment]
Hi,

I've had a chance to get back to looking at this. I'm now running on a linux machine (CENTOS 7, lxplus) and have the following python virtual environment set up:

```
Package                       Version
----------------------------- -------
awkward                       0.9.0
backports.functools-lru-cache 1.5
cachetools                    3.1.0
cycler                        0.10.0
Cython                        0.29.7
EnergyFlow                    0.12.2
kiwisolver                    1.1.0
matplotlib                    2.2.4
numpy                         1.16.3
pip                           19.1.1
POT                           0.5.1
pyparsing                     2.4.0
python-dateutil               2.8.0
pytz                          2019.1
scipy                         1.2.1
setuptools                    28.8.0
six                           1.12.0
subprocess32                  3.5.3
uproot                        3.5.2
uproot-methods                0.5.1
wheel                         0.29.0
```

... I am trying to run the EMDs command on the following two jets, with no further processing. As previously, I still get the out-of-simplex error if I set `norm=True` in the `emds` call.

```
# jet  0: pt,y,phi
[[ 1.28805250e-01  1.24707185e-02  3.00127316e+00]
 [ 7.32726753e-01  4.55578715e-01  3.57829452e+00]
 [ 1.54215074e+00  4.07914072e-01  3.00949812e+00]
 [ 1.49775374e+00 -2.37689354e-03  3.20451331e+00]
 [ 1.34802914e+00  4.80275095e-01  3.30638051e+00]
 [ 4.89076883e-01  3.99124086e-01  3.16334629e+00]
 [ 2.60517883e+00  4.15289044e-01  3.33741975e+00]
 [ 2.70545650e+00  2.91676760e-01  3.13696480e+00]
 [ 4.93863970e-02  1.42762020e-01  3.17519331e+00]
 [ 1.26911945e+01  3.45387667e-01  3.17020559e+00]
 [ 6.44490051e+00  3.19200456e-01  3.33573103e+00]
 [ 1.61877518e+01  3.09240729e-01  3.25527978e+00]
 [ 3.42575860e+00  3.05735409e-01  3.27306366e+00]
 [ 1.23199692e+01  2.85261959e-01  3.27364612e+00]
 [ 9.44843006e+00  2.83916116e-01  3.32487988e+00]
 [ 4.34369946e+00  1.97724611e-01  3.29247451e+00]
 [ 1.44992864e+00  2.55433828e-01  3.34256959e+00]
 [ 4.10949707e+00  2.84942180e-01  3.29029632e+00]
 [ 1.81374569e+01  2.10627049e-01  3.30056572e+00]
 [ 8.30980778e+00  2.15563402e-01  3.30613232e+00]
 [ 7.59618568e+00  2.34774172e-01  3.27284598e+00]
 [ 2.97300091e+01  2.42869571e-01  3.27123451e+00]
 [ 1.85150604e+01  2.17747480e-01  3.29484701e+00]
 [ 2.63931847e+01  2.20370799e-01  3.30681396e+00]
 [ 8.67043915e+01  2.24240214e-01  3.29330611e+00]
 [ 4.31435204e+01  2.28416085e-01  3.28882122e+00]
 [ 1.44696684e+01  2.48087242e-01  3.32776284e+00]
 [ 3.55158234e+01  2.32842222e-01  3.31091189e+00]
 [ 4.11248875e+00  2.49088868e-01  3.28296781e+00]
 [ 3.07104816e+01  2.40688801e-01  3.30709147e+00]
 [ 2.54982853e+01  2.43221283e-01  3.29352832e+00]
 [ 2.80090008e+01  2.50426829e-01  3.31078792e+00]
 [ 8.26018906e+01  2.59926945e-01  3.30893588e+00]
 [ 2.06580200e+01  2.62850851e-01  3.30188632e+00]
 [ 7.42874289e+00  2.62752026e-01  3.29896808e+00]
 [ 6.39859962e+00  2.60584056e-01  3.30027366e+00]
 [ 4.21969376e+01  2.58597463e-01  3.30021000e+00]
 [ 9.74676819e+01  2.58068085e-01  3.29915404e+00]
 [ 4.83042068e+01  2.58799076e-01  3.29879642e+00]
 [ 3.21322966e+00  3.69048566e-01  3.06917000e+00]
 [ 1.12345047e+01  3.72081786e-01  3.06988263e+00]
 [ 3.08946266e+01  3.65932047e-01  3.12945461e+00]
 [ 1.65618646e+00  3.71579915e-01  3.08576083e+00]
 [ 4.92267370e+00  3.62950981e-01  3.12388730e+00]
 [ 1.39230585e+01  3.55340481e-01  3.11263466e+00]
 [ 9.29178333e+00  3.68443310e-01  3.09082007e+00]
 [ 2.44735742e+00  3.84619802e-01  3.10587001e+00]
 [ 9.40637207e+01  3.70552838e-01  3.10696220e+00]]

# jet  1: pt,y,phi
[[2.56437254e+00 6.67872429e-01 5.87835550e+00]
 [1.78110337e+00 3.60959351e-01 5.47259474e+00]
 [7.09249377e-01 4.86216486e-01 5.77115440e+00]
 [2.78075874e-01 3.96285057e-01 5.35382843e+00]
 [1.60130680e+00 4.02348906e-01 5.34968615e+00]
 [1.00257230e+00 4.22893912e-01 5.35315943e+00]
 [1.30218959e+00 5.55959225e-01 5.76712132e+00]
 [1.07943326e-01 9.66618299e-01 5.63222408e+00]
 [7.69793928e-01 5.51739931e-01 5.26956987e+00]
 [1.62867939e+00 6.69201493e-01 5.29552174e+00]
 [9.11115259e-02 8.97457361e-01 5.57761335e+00]
 [3.06131363e-01 6.38916075e-01 5.33193254e+00]
 [1.32626331e+00 7.94341326e-01 5.65017986e+00]
 [3.40524137e-01 8.26721549e-01 5.61297655e+00]
 [5.23225367e-01 5.67005098e-01 5.56447077e+00]
 [5.84825611e+00 7.17280209e-01 5.35827494e+00]
 [1.43660414e+00 7.96178579e-01 5.39659739e+00]
 [1.71162355e+00 7.80852675e-01 5.60646105e+00]
 [1.08446844e-01 7.36312389e-01 5.38451290e+00]
 [6.51543808e+00 6.64583325e-01 5.42489767e+00]
 [3.21418715e+00 6.35562301e-01 5.45538187e+00]
 [2.04129076e+00 6.78977489e-01 5.58094263e+00]
 [7.41373420e-01 7.80339241e-01 5.48656559e+00]
 [7.45369577e+00 7.76129663e-01 5.47766066e+00]
 [6.16767693e+00 6.48813725e-01 5.52455091e+00]
 [2.25822401e+00 7.44244218e-01 5.45550537e+00]
 [7.12062550e+00 7.28601336e-01 5.45865726e+00]
 [1.70402584e+01 7.22488463e-01 5.45916080e+00]
 [8.61002445e+00 7.32430458e-01 5.46419477e+00]
 [3.14973378e+00 6.89675331e-01 5.48079729e+00]
 [3.19449100e+01 7.02656627e-01 5.48434114e+00]
 [1.91811955e+00 6.93134546e-01 5.49738836e+00]
 [7.90378666e+00 7.18467057e-01 5.50993299e+00]
 [4.06099510e+01 7.02885211e-01 5.51688671e+00]
 [3.20405006e+01 7.06427991e-01 5.50651407e+00]
 [1.02017929e+02 7.11703658e-01 5.50893497e+00]
 [3.07010193e+01 7.11019278e-01 5.51017666e+00]
 [9.75068130e+01 7.09011197e-01 5.50874376e+00]
 [2.73828278e+01 7.07548261e-01 5.50918388e+00]
 [1.74374657e+01 7.06726849e-01 5.51357460e+00]
 [1.83738632e+02 7.08337069e-01 5.51192427e+00]
 [1.32812786e+01 7.09893286e-01 5.51206446e+00]]
```

I call the `emds` function like:

```
my_emds = ef.emd.emds(jets, R=0.4, gdim=2, n_iter_max=100000, phi_col=2, n_jobs=16, verbose=1, print_every=25000, norm=True)
```
If I run without `norm=True`, I get an EMD of 4053.85836375 for these two jets (I suppose it's large due to no preprocessing, etc.).

**Comment by pkomiske** [comment]
Hi Matt,

I have tried running this on a CentOS 7 server that I just made on the Google Cloud with python 2.7.5 with the package versions you give above and I still do not find any issues. I get your reported result for `norm=False` and for `norm=True` I get 5.71587207.

One thing that is not identical between what we're trying is that the jets you gave above aren't quite accurate to double floating point precision (only so many digits get printed by default), and it's almost certain that the issue is with some floating point arithmetic inside pot.

If you send me a public ssh key I can give you access to this server so you can see for yourself and/or try other things, if you want.

**Comment by ericmetodiev** [comment]
Hi Matt,

To quickly test whether it is a specific floating point arithmetic issue, you could try to slightly perturb the jets and see if the issue persists.
`jets *= 1 + 10**-6`

**Comment by mattleblanc** [comment]
I think this was it! If I limit the floatng-point precision of my arrays using `np.around`, it seems to run well. I get a value of 5.71585794 with `norm=True` for the above jets and 9 decimal places ... close enough for these studies, I think. Running on sets of many jets also works.

Thanks again for the help! 🍻
